name       : gpxsee
version    : 10.1
release    : 1
source     :
    - https://github.com/tumic0/GPXSee/archive/refs/tags/10.1.tar.gz : 4ca12ceba43c1e96247cb4affc5372bc31c492d7b8e288f929c8c409a1f84440
license    : GPL-3.0-or-later
component  : desktop
summary    : a Qt-based GPS log file viewer and analyzer that supports all common GPS log file formats.
description: |
    a Qt-based GPS log file viewer and analyzer that supports all common GPS log file formats.
builddeps  :
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release gpxsee.pro PREFIX=%PREFIX%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
