name       : gpxsee
version    : '11.5'
release    : 14
source     :
    - https://github.com/tumic0/GPXSee/archive/refs/tags/11.5.tar.gz : 71d76e3a95e5c9454963e52d3a582eaa6945d1f1dd625e1f8074abdb43310178
license    : GPL-3.0-or-later
component  : desktop
summary    : a Qt-based GPS log file viewer and analyzer that supports all common GPS log file formats.
description: |
    a Qt-based GPS log file viewer and analyzer that supports all common GPS log file formats.
builddeps  :
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release gpxsee.pro PREFIX=%PREFIX%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
