name       : gpxsee
version    : '13.2'
release    : 20
source     :
    - https://github.com/tumic0/GPXSee/archive/refs/tags/13.2.tar.gz : 1e56b7df7dd36ccd270dc0e7666b9e1c18d6b7ec73ca39b025356e4f5bc634f6
license    : GPL-3.0-or-later
component  : desktop
summary    : a Qt-based GPS log file viewer and analyzer that supports all common GPS log file formats.
description: |
    a Qt-based GPS log file viewer and analyzer that supports all common GPS log file formats.
builddeps  :
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release gpxsee.pro PREFIX=%PREFIX%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
