name       : gpxsee
version    : '12.4'
release    : 19
source     :
    - https://github.com/tumic0/GPXSee/archive/refs/tags/12.4.tar.gz : c5e3fe4fb4315c1c1b5aa2ee51af6f4baed5f3ed0215f3d9bc4c8370605254f6
license    : GPL-3.0-or-later
component  : desktop
summary    : a Qt-based GPS log file viewer and analyzer that supports all common GPS log file formats.
description: |
    a Qt-based GPS log file viewer and analyzer that supports all common GPS log file formats.
builddeps  :
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release gpxsee.pro PREFIX=%PREFIX%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
