name       : gpxsee
version    : 10.2
release    : 3
source     :
    - https://github.com/tumic0/GPXSee/archive/refs/tags/10.2.tar.gz : 62b7efaeefe5d91b214f249af3bca08feb1e9282d375683295df01fb88b2125d
license    : GPL-3.0-or-later
component  : desktop
summary    : a Qt-based GPS log file viewer and analyzer that supports all common GPS log file formats.
description: |
    a Qt-based GPS log file viewer and analyzer that supports all common GPS log file formats.
builddeps  :
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake CONFIG+=release gpxsee.pro PREFIX=%PREFIX%
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
